### ISSUE TITLE
icons not installed correctly

### ISSUE THREAD

**Issue by bdarcus** [hevanaa/oscar-spec#1]
Just adding [this](http://www.apneaboard.com/forums/Thread-OSCAR-Release-v1-1-0?pid=348605#pid348605) here:

> Turns out icons have changed throughout the OSCAR development. To the better, because now the repo seems to contain all needed icons as per the freedesktop specification (except 96x96 if we are really picky). I need to update the spec to install correct icons (and to correct places). Now the 48x48 icon was missing due to these changes. In X11 it works, because it falls back to the application name by looking for the WM_CLASS window property (which is correctly set by OSCAR) if icon isn't found. But Wayland doesn't have a fallback for finding icons.

**Comment by hevanaa** [comment]
I've created a new build. There are some issues in Gnome, because I think Oscar doesn't implement the GtkApplication API. So I've changed the desktop file name to the new standard and added WM_CLASS property into it. Now it works in Wayland, but there is still, at least in my desktop, some idle time before the application is available in the window switcher (Alt-tab). This, I believe is when it is searching for the correct icon. Another good effect is that now the icon should be good looking in different display resolutions. In the stock Oscar desktop file, the icon path is hard coded, which makes it look low resolution in high resolution displays.

**Comment by bdarcus** [comment]
Thanks.

For some reason that I don't understand, copr isn't updating for me, despite this returned from `dnf info oscar`.

```
Installed Packages
Name         : oscar
Version      : 1.1.0
Release      : 1.fc32
...

Available Packages
Name         : oscar
Version      : 1.1.0
Release      : 2.fc32
```

**Comment by hevanaa** [comment]
Repos are being slow today. Wait, I will create a new build to also fix another build issue (https://gitlab.com/pholy/OSCAR-code/-/issues/19#).

**Comment by bdarcus** [comment]
Sure thing.

Oh wow; OSCAR finally has a public issue tracker!

**Comment by hevanaa** [comment]
Nah, the last failed on epel7. Need to do further testing with that. But you should be able to update with "sudo dnf update --refresh" (works for me).

**Comment by bdarcus** [comment]
Confirmed. Thanks again.
